#!/usr/bin/env bash
# SSH client configuration

Host *
    PasswordAuthentification no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentification yes
    GSSAPIDelegateCredential no
